export const voiceovers = [
  {
    id: "opening",
    start: 0.6,
    end: 11.6,
    text: "We already ask ChatGPT what to buy. But actually buying still means opening tabs, checking compatibility, finding stock, and rebuilding everything at checkout. We built Woven to finish that process.",
    spoken: "We already ask Chat G P T what to buy. But actually buying still means opening tabs, checking compatibility, finding stock, and rebuilding everything at checkout. We built Woven to finish that process.",
  },
  {
    id: "problem",
    start: 12.6,
    end: 29.4,
    text: "Imagine planning a first camping trip for two on a rainy weekend. Search can recommend a tent, but it does not guarantee rainproof shelter, two complete sleep systems, lighting and first aid, one-car fit, budget, stock, and one pickup location.",
    spoken: "Imagine planning a first camping trip for two on a rainy weekend. Search can recommend a tent, but it does not guarantee rainproof shelter, two complete sleep systems, lighting and first aid, one-car fit, budget, stock, and one pickup location.",
  },
  {
    id: "complete-cart",
    start: 30.6,
    end: 47.0,
    text: "Woven understands the complete request, eliminates incompatible combinations, and creates ready-to-buy carts. Every cart comes from one merchant and one location, with proof that every component and quantity fits the same trip.",
    spoken: "Woven understands the complete request, eliminates incompatible combinations, and creates ready-to-buy carts. Every cart comes from one merchant and one location, with proof that every component and quantity fits the same trip.",
  },
  {
    id: "ask-once",
    start: 58,
    end: 83,
    text: "Woven returned five complete options—not loose product links. This S$231.00 cart includes a rainproof tent, a sleeping bag and mat for each camper, an IPX4 lantern, and water-resistant first aid. All seven required units fit one car boot, stay under budget, and are ready at one pickup location.",
    spoken: "Woven returned five complete options, not loose product links. This two hundred thirty-one Singapore dollar cart includes a rainproof tent, a sleeping bag and mat for each camper, an I P X four lantern, and water-resistant first aid. All seven required units fit one car boot, stay under budget, and are ready at one pickup location.",
  },
  {
    id: "review-once",
    start: 96.2,
    end: 117.8,
    text: "Before checkout, Woven enforces a simulated identity handoff, then rechecks price and stock. The AI cannot approve the purchase. The user sees every item and quantity, the pickup location, and the S$231.00 total before one direct confirmation.",
    spoken: "Before checkout, Woven enforces a simulated identity handoff, then rechecks price and stock. The A I cannot approve the purchase. The user sees every item and quantity, the pickup location, and the two hundred thirty-one Singapore dollar total before one direct confirmation.",
  },
  {
    id: "confirm-once",
    start: 119.2,
    end: 133.8,
    text: "Only after that click does Woven produce a simulated Visa authorization and pickup receipt. No card details enter Woven, and no live charge occurs.",
    spoken: "Only after that click does Woven produce a simulated Visa authorization and pickup receipt. No card details enter Woven, and no live charge occurs.",
  },
  {
    id: "merchant-control",
    start: 136.6,
    end: 153.8,
    text: "On the merchant side, Woven already supports inventory import, price and stock controls, orders, and an audit trail. Merchants can simulate a price change, stockout, authorization decline, or reversal without changing code.",
    spoken: "On the merchant side, Woven already supports inventory import, price and stock controls, orders, and an audit trail. Merchants can simulate a price change, stockout, authorization decline, or reversal without changing code.",
  },
  {
    id: "why-chat",
    start: 155,
    end: 166.8,
    text: "Why ChatGPT? Because that is where the user’s request already exists. Why a plugin? Because Woven can turn that conversation into merchant actions and a reviewable checkout without asking the user to start again.",
    spoken: "Why Chat G P T? Because that is where the user's request already exists. Why a plug-in? Because Woven can turn that conversation into merchant actions and a reviewable checkout without asking the user to start again.",
  },
  {
    id: "truth-boundary",
    start: 166.8,
    end: 174.5,
    text: "This prototype uses seeded inventory, a server-enforced demo identity check, and a simulated Visa authorization. No live charge occurs.",
    spoken: "This prototype uses seeded inventory, a server-enforced demo identity check, and a simulated Visa authorization. No live charge occurs.",
  },
  {
    id: "final-line",
    start: 174.5,
    end: 179.7,
    text: "Woven makes shopping through AI simple enough to use—and controlled enough to trust.",
    spoken: "Woven makes shopping through A I simple enough to use, and controlled enough to trust.",
  },
] as const;
