export const voiceovers = [
  {
    id: "opening",
    start: 0.6,
    end: 11.6,
    text: "We already ask ChatGPT what to buy. But actually buying still means opening tabs, checking compatibility, finding stock, and rebuilding everything at checkout. We built Woven to finish that process.",
    spoken: "We already ask Chat G P T what to buy. But actually buying still means opening tabs, checking compatibility, finding stock, and rebuilding everything at checkout. We built Woven to finish that process.",
  },
  {
    id: "problem",
    start: 12.6,
    end: 29.4,
    text: "Imagine flying tonight and needing a charger for three devices. Search can recommend individual products, but it does not guarantee that everything works together, fits your budget, is available today, and can be collected from one place.",
    spoken: "Imagine flying tonight and needing a charger for three devices. Search can recommend individual products, but it does not guarantee that everything works together, fits your budget, is available today, and can be collected from one place.",
  },
  {
    id: "complete-cart",
    start: 30.6,
    end: 47.0,
    text: "Woven understands the complete request, eliminates incompatible combinations, and creates ready-to-buy carts. Every cart comes from one merchant and one location, with an explanation of why every component works.",
    spoken: "Woven understands the complete request, eliminates incompatible combinations, and creates ready-to-buy carts. Every cart comes from one merchant and one location, with an explanation of why every component works.",
  },
  {
    id: "ask-once",
    start: 58,
    end: 83,
    text: "Woven returned three complete options—not loose product links. This S$133 cart includes the charger, both required cables, and the Japan adapter. Everything is compatible, under budget, available in our demo inventory, and ready at one pickup location.",
    spoken: "Woven returned three complete options, not loose product links. This one hundred and thirty-three Singapore dollar cart includes the charger, both required cables, and the Japan adapter. Everything is compatible, under budget, available in our demo inventory, and ready at one pickup location.",
  },
  {
    id: "review-once",
    start: 96.2,
    end: 117.8,
    text: "Woven rechecks the price and stock, then creates an exact ten-minute checkout preview. The AI recommended this cart, but it cannot approve it. The user sees the merchant, every item, the pickup location, and the S$133 total before one direct confirmation.",
    spoken: "Woven rechecks the price and stock, then creates an exact ten-minute checkout preview. The A I recommended this cart, but it cannot approve it. The user sees the merchant, every item, the pickup location, and the one hundred and thirty-three Singapore dollar total before one direct confirmation.",
  },
  {
    id: "confirm-once",
    start: 119.2,
    end: 133.8,
    text: "Only after that click does Woven produce a simulated Visa authorization and pickup receipt. No card details enter Woven, and no live charge occurs.",
    spoken: "Only after that click does Woven produce a simulated Visa authorization and pickup receipt. No card details enter Woven, and no live charge occurs.",
  },
  {
    id: "merchant-control",
    start: 136.6,
    end: 153.8,
    text: "On the merchant side, Woven already supports inventory import, price and stock controls, orders, and an audit trail. Merchants can simulate a price change, stockout, authorization decline, or reversal without changing code.",
    spoken: "On the merchant side, Woven already supports inventory import, price and stock controls, orders, and an audit trail. Merchants can simulate a price change, stockout, authorization decline, or reversal without changing code.",
  },
  {
    id: "why-chat",
    start: 155,
    end: 166.8,
    text: "Why ChatGPT? Because that is where the user’s request already exists. Why a plugin? Because Woven can turn that conversation into merchant actions and a reviewable checkout without asking the user to start again.",
    spoken: "Why Chat G P T? Because that is where the user's request already exists. Why a plug-in? Because Woven can turn that conversation into merchant actions and a reviewable checkout without asking the user to start again.",
  },
  {
    id: "truth-boundary",
    start: 166.8,
    end: 174.5,
    text: "This prototype uses seeded inventory and a simulated Visa authorization; no live charge occurs. Our next trust step is the connector-style demo identity check.",
    spoken: "This prototype uses seeded inventory and a simulated Visa authorization. No live charge occurs. Our next trust step is the connector-style demo identity check.",
  },
  {
    id: "final-line",
    start: 174.5,
    end: 179.7,
    text: "Woven makes shopping through AI simple enough to use—and controlled enough to trust.",
    spoken: "Woven makes shopping through A I simple enough to use, and controlled enough to trust.",
  },
] as const;
