export const voiceovers = [
  {
    id: "opening",
    start: 0.6,
    end: 11.6,
    text: "We already ask ChatGPT what to buy. But actually buying still means opening tabs, checking compatibility, finding stock, and rebuilding everything at checkout. We built Woven to finish that process.",
    spoken: "We already ask Chat G P T what to buy. But actually buying still means opening tabs, checking compatibility, finding stock, and rebuilding everything at checkout. We built Woven to finish that process.",
  },
  {
    id: "problem",
    start: 12.6,
    end: 29.4,
    text: "Imagine planning a first camping trip for two on a rainy weekend. Search can recommend a tent, but it does not guarantee rainproof shelter, two complete sleep systems, lighting and first aid, one-car fit, budget, stock, and one pickup location.",
    spoken: "Imagine planning a first camping trip for two on a rainy weekend. Search can recommend a tent, but it does not guarantee rainproof shelter, two complete sleep systems, lighting and first aid, one-car fit, budget, stock, and one pickup location.",
  },
  {
    id: "complete-cart",
    start: 30.6,
    end: 47.0,
    text: "Woven understands the complete request, eliminates incompatible combinations, and creates ready-to-buy carts. Every cart comes from one merchant and one location, with proof that every component and quantity fits the same trip.",
    spoken: "Woven understands the complete request, eliminates incompatible combinations, and creates ready-to-buy carts. Every cart comes from one merchant and one location, with proof that every component and quantity fits the same trip.",
  },
  {
    id: "ask-once",
    start: 58,
    end: 83,
    text: "Woven returned five complete options—not loose product links. This S$231.00 cart includes a rainproof tent, a sleeping bag and mat for each camper, an IPX4 lantern, and water-resistant first aid. All seven required units fit one car boot, stay under budget, and are ready at one pickup location.",
    spoken: "Woven returned five complete options, not loose product links. This two hundred thirty-one Singapore dollar cart includes a rainproof tent, a sleeping bag and mat for each camper, an I P X four lantern, and water-resistant first aid. All seven required units fit one car boot, stay under budget, and are ready at one pickup location.",
  },
  {
    id: "review-once",
    start: 96.2,
    end: 117.8,
    text: "Before checkout, Woven enforces a simulated identity handoff, then rechecks price and stock. The AI cannot approve the purchase. The user sees every item and quantity, the pickup location, and the S$231.00 total before one direct confirmation.",
    spoken: "Before checkout, Woven enforces a simulated identity handoff, then rechecks price and stock. The A I cannot approve the purchase. The user sees every item and quantity, the pickup location, and the two hundred thirty-one Singapore dollar total before one direct confirmation.",
  },
  {
    id: "confirm-once",
    start: 119.2,
    end: 133.8,
    text: "Only after that click does Woven produce a simulated Visa authorization and pickup receipt. No card details enter Woven, and no live charge occurs.",
    spoken: "Only after that click does Woven produce a simulated Visa authorization and pickup receipt. No card details enter Woven, and no live charge occurs.",
  },
  {
    id: "merchant-control",
    start: 136.6,
    end: 153.8,
    text: "On the merchant side, Woven already supports inventory import, price and stock controls, orders, and an audit trail. Merchants can simulate a price change, stockout, authorization decline, or reversal without changing code.",
    spoken: "On the merchant side, Woven already supports inventory import, price and stock controls, orders, and an audit trail. Merchants can simulate a price change, stockout, authorization decline, or reversal without changing code.",
  },
  {
    id: "why-chat",
    start: 155,
    end: 166.8,
    text: "Why ChatGPT? Because that is where the user’s request already exists. Why a plugin? Because Woven can turn that conversation into merchant actions and a reviewable checkout without asking the user to start again.",
    spoken: "Why Chat G P T? Because that is where the user's request already exists. Why a plug-in? Because Woven can turn that conversation into merchant actions and a reviewable checkout without asking the user to start again.",
  },
  {
    id: "truth-boundary",
    start: 166.8,
    end: 174.5,
    text: "This prototype uses seeded inventory, a server-enforced demo identity check, and a simulated Visa authorization. No live charge occurs.",
    spoken: "This prototype uses seeded inventory, a server-enforced demo identity check, and a simulated Visa authorization. No live charge occurs.",
  },
  {
    id: "final-line",
    start: 174.5,
    end: 179.7,
    text: "Woven makes shopping through AI simple enough to use—and controlled enough to trust.",
    spoken: "Woven makes shopping through A I simple enough to use, and controlled enough to trust.",
  },
] as const;

export const webMcpVoiceovers = [
  {
    id: "opening",
    start: 0.5,
    end: 11.8,
    text: "Shopping agents can suggest products. Woven uses WebMCP to finish a multi-item mission: one request, seven site tools, complete verified carts, and a human-only purchase boundary.",
    spoken: "Shopping agents can suggest products. Woven uses Web M C P to finish a multi-item mission: one request, seven site tools, complete verified carts, and a human-only purchase boundary.",
  },
  {
    id: "live-tools",
    start: 12.4,
    end: 48.5,
    text: "Here is the live, top-level Woven Trail Market storefront. The browser discovers seven purpose-built tools: start or inspect a mission, compare and select carts, apply an approved swap, refresh price and stock, and verify an existing receipt. When the agent calls start_mission, the same page the person sees moves from idle to verified kits. Tool calls and human review share one state. There is no DOM guessing, and no separate agent-only result.",
    spoken: "Here is the live, top-level Woven Trail Market storefront. The browser discovers seven purpose-built tools: start or inspect a mission, compare and select carts, apply an approved swap, refresh price and stock, and verify an existing receipt. When the agent calls start mission, the same page the person sees moves from idle to verified kits. Tool calls and human review share one state. There is no D O M guessing, and no separate agent-only result.",
  },
  {
    id: "mission",
    start: 52.4,
    end: 68.7,
    text: "Our test mission is a rainy-weekend camping kit for two, under S$300, in one car boot, pickup-ready today. Woven has to satisfy quantity, weather, compatibility, volume, current stock, budget, and one pickup location at the same time.",
    spoken: "Our test mission is a rainy-weekend camping kit for two, under three hundred Singapore dollars, in one car boot, pickup-ready today. Woven has to satisfy quantity, weather, compatibility, volume, current stock, budget, and one pickup location at the same time.",
  },
  {
    id: "verified-result",
    start: 70.4,
    end: 88.5,
    text: "Woven verifies five complete candidates and shows the best two. TrailHaus is 7 units across 5 required categories, 89 L packed, a 3,000 mm rainfly, and an exact S$231 total from one pickup point. These are checkout-quality facts, not search snippets.",
    spoken: "Woven verifies five complete candidates and shows the best two. TrailHaus is seven units across five required categories, eighty-nine liters packed, a three-thousand-millimeter rainfly, and an exact two-hundred-thirty-one Singapore dollar total from one pickup point. These are checkout-quality facts, not search snippets.",
  },
  {
    id: "human-boundary",
    start: 89,
    end: 130.5,
    text: "The agent may rerank the kits, select one, or apply only a merchant-approved compatible alternative. Then it stops. Identity, exact checkout terms, confirmation secrets, and purchase authorization are deliberately absent from the WebMCP tool surface. The person completes the simulated identity handoff, sees every item, quantity, merchant, pickup point, total, and expiry, then confirms directly. Only that click can produce the simulated Visa result; Woven accepts no card credentials and cannot make a live charge.",
    spoken: "The agent may rerank the kits, select one, or apply only a merchant-approved compatible alternative. Then it stops. Identity, exact checkout terms, confirmation secrets, and purchase authorization are deliberately absent from the Web M C P tool surface. The person completes the simulated identity handoff, sees every item, quantity, merchant, pickup point, total, and expiry, then confirms directly. Only that click can produce the simulated Visa result. Woven accepts no card credentials and cannot make a live charge.",
  },
  {
    id: "implementation",
    start: 133.3,
    end: 152,
    text: "Implementation is equally explicit. The top-level document supplies modelContext; Woven registers seven tools with closed schemas, read-only annotations where appropriate, and one AbortSignal that removes the tool surface on navigation. Every call enters the same server router and deterministic verifier used by the visible storefront.",
    spoken: "Implementation is equally explicit. The top-level document supplies model context. Woven registers seven tools with closed schemas, read-only annotations where appropriate, and one abort signal that removes the tool surface on navigation. Every call enters the same server router and deterministic verifier used by the visible storefront.",
  },
  {
    id: "closing",
    start: 154,
    end: 176.5,
    text: "Woven shows what people and agents can do together: the agent handles reversible preparation, the server enforces commerce truth, and the person owns identity and purchase. The live app, public source, and demo are ready for review. Seeded inventory, simulated identity, simulated payment—no live charge.",
    spoken: "Woven shows what people and agents can do together: the agent handles reversible preparation, the server enforces commerce truth, and the person owns identity and purchase. The live app, public source, and demo are ready for review. Seeded inventory, simulated identity, simulated payment. No live charge.",
  },
] as const;
